FROM rhel8/go-toolset:1.12.8 AS builder
WORKDIR /opt/app-root/src/go/src/knative.dev/LServing
COPY . .
RUN go build -o /tmp/LNetworking-CertManager ./cmd/LNetworking-CertManager

FROM ubi8:8-released
COPY --from=builder /tmp/LNetworking-CertManager /ko-app/LNetworking-CertManager

LABEL \
      com.redhat.component="openshift-serverless-1-tech-preview-LServing-LNetworking-CertManager-rhel8-container" \
      name="openshift-serverless-1-tech-preview/LServing-LNetworking-CertManager-rhel8" \
      version="" \
      summary="Red Hat OpenShift Serverless 1 Serving Networking CertManager" \
      maintainer="serverless-support@redhat.com" \
      description="Red Hat OpenShift Serverless 1 Serving Networking CertManager" \
      io.k8s.display-name="Red Hat OpenShift Serverless 1 Serving Networking CertManager"

ENTRYPOINT ["/ko-app/LNetworking-CertManager"]
