FROM rhel8/go-toolset:1.13.4 AS builder
WORKDIR /opt/app-root/src/go/src/knative.dev/serving
COPY . .
ENV GOFLAGS="-mod=vendor -tags=disable_gcp,disable_aws,disable_azure"
RUN go build -o /tmp/controller ./cmd/controller

FROM ubi8-minimal:8-released
COPY --from=builder /tmp/controller /ko-app/controller

LABEL \
      com.redhat.component="openshift-serverless-1-tech-preview-serving-controller-rhel8-container" \
      name="openshift-serverless-1-tech-preview/serving-controller-rhel8" \
      version="v0.13.3" \
      summary="Red Hat OpenShift Serverless 1 Serving Controller" \
      maintainer="serverless-support@redhat.com" \
      description="Red Hat OpenShift Serverless 1 Serving Controller" \
      io.k8s.display-name="Red Hat OpenShift Serverless 1 Serving Controller"

ENTRYPOINT ["/ko-app/controller"]
