FROM rhel8/go-toolset:1.12.8 AS builder
WORKDIR /opt/app-root/src/go/src/knative.dev/serving
COPY . .
RUN go build -o /tmp/controller ./cmd/controller

FROM ubi8:8-released
COPY --from=builder /tmp/controller /ko-app/controller

LABEL \
      com.redhat.component="openshift-serverless-1-tech-preview-serving-controller-rhel8-container" \
      name="openshift-serverless-1-tech-preview/serving-controller-rhel8" \
      version="0.9.0" \
      summary="Red Hat OpenShift Serverless 1 Serving Controller" \
      maintainer="serverless-support@redhat.com" \
      description="Red Hat OpenShift Serverless 1 Serving Controller" \
      io.k8s.display-name="Red Hat OpenShift Serverless 1 Serving Controller"

ENTRYPOINT ["/ko-app/controller"]
