FROM rhel8/go-toolset:1.12.8 AS builder
WORKDIR /opt/app-root/src/go/src/knative.dev/serving
COPY . .
RUN go build -o /tmp/networking-certmanager ./cmd/networking/certmanager

FROM ubi8:8-released
COPY --from=builder /tmp/networking-certmanager /ko-app/networking-certmanager

LABEL \
      com.redhat.component="openshift-serverless-1-tech-preview-serving-networking-certmanager-rhel8-container" \
      name="openshift-serverless-1-tech-preview/serving-networking-certmanager-rhel8" \
      version="0.9.0" \
      summary="Red Hat OpenShift Serverless 1 Serving Networking CertManager" \
      maintainer="wvanwinc@redhat.com" \
      description="Red Hat OpenShift Serverless 1 Serving Networking CertManager" \
      io.k8s.display-name="Red Hat OpenShift Serverless 1 Serving Networking CertManager"

ENTRYPOINT ["/ko-app/networking-certmanager"]
