FROM rhel8/go-toolset:1.12.8 AS builder
WORKDIR /opt/app-root/src/go/src/knative.dev/serving
COPY . .
RUN go build -o /tmp/$SUBCOMPONENT ./cmd/$GO_PACKAGE

FROM ubi8:8-released
COPY --from=builder /tmp/$SUBCOMPONENT /usr/bin/$SUBCOMPONENT

LABEL \
      com.redhat.component="openshift-serverless-1-tech-preview-serving-$SUBCOMPONENT-rhel8-container" \
      name="openshift-serverless-1-tech-preview/serving-$SUBCOMPONENT-rhel8" \
      version="0.8.1" \
      summary="Red Hat OpenShift Serverless 1 Serving $CAPITALIZED_SUBCOMPONENT" \
      maintainer="wvanwinc@redhat.com" \
      description="Red Hat OpenShift Serverless 1 Serving $CAPITALIZED_SUBCOMPONENT" \
      io.k8s.display-name="Red Hat OpenShift Serverless 1 Serving $CAPITALIZED_SUBCOMPONENT"

ENTRYPOINT ["/usr/bin/$SUBCOMPONENT"]
